### PR TITLE
Add FPU

### PR DESCRIPTION
**Pull request by CKeilbar**
This pull request adds a high-performance FPU for full support for the floating-point F and D RISC-V ISA extensions.
The FPU is fully IEEE-754 compliant, supporting all rounding modes, exceptions, and numerical correctness.

FPU correctness was verified using [this repository](https://gitlab.com/sfu-rcl/fpu-tests), which contains test vectors for all combinations of floating-point instruction and rounding mode. There are ~60 million test cases in total, the vast majority being drawn from the [Berkeley TestFloat program](http://www.jhauser.us/arithmetic/TestFloat.html).

On the ZedBoard, including the FPU adds about ~7,500 LUTs, ~3,500 FFs, and 9 DSPs, and reduces the frequency by ~20MHz.
This cost is worthwhile for applications using floating-point numbers, as emulating floating-point operations in software has overhead on the order of 100x.

The FPU also supports parameterizable single and double reduced-precision number formats, which trades off numerical accuracy for performance and area.

After this is merged, PR #16 can be closed and accelerators-2023 can be deleted, as the FPU includes the changes from both.

### CODE REVIEW

**Review by e-matthews — APPROVED** [review]
I have gone over the changes for the FPU at a high level and have tested non-FPU config to confirm that there isn't an impact on the performance/functionality if the FPU is not included.  This pull request may be merged as is.

**Comment by CKeilbar** [comment]
So I've spent the day trying to sort this out. I encountered many (many) problems. Using git rebase to try and change the author of the problematic commit does not work, as git rebase complains about merge conflicts (even if nothing is changed by the rebase). I did some digging and apparently this is a problem caused by nonlinear branch histories.

I am however capable of changing the author of commits using git filter-repo, or git replace.

This repo contains the following commit, which was written by Gao in 2021 and committed by Eric in 2022.
image

The FPU repo contains this commit in addition to this original commit, which was both authored and committed by Gao in 2021:
image

This is the commit that blocks the licensing check, as it has a server address instead of a valid email. My plan was to change the email for this second commit to his personal Gmail address, and then have Gao sign the ECA using that email address. However, as you can see, making this change creates merge conflicts in this repository with commit baf91ea278a8fda494f9f83c2c1a70bfd2f7b25d, which was the first signed commit. Whether I use git filter-repo or git replace, what happens is it creates an *unsigned* version of this commit on ck-cva5/fpu. As a result, this unsigned commit has a different SHA (d6e3ab25ef31d348c0b47f46857381b500af13bf) than the same commit on ck-cva5/master (which matches the SHA on this repository), causing GitHub to reject this merge request.

As best I can tell, I cannot modify the problematic author email field for this old commit while preserving the signature. To me, this suggests only two possible options:
1. Bypass the ECA check on this merge request
2. Squash the FPU portions of this merge request into one commit with me as the author. Note that all original authors will be credited in the header of each file regardless of the option.

Please let me know what you think we should do.

**Comment by DBees** [comment]
@MikeOpenHWGroup SFU is a supporter member and doesn't have an MCCA on file thus we need to rely on individual ECA in this case. 
@CKeilbar thank you for this diligence. A complex situation. Can you please ask Gao to sign the ECA? I'm looking into how to accept the pull request given that he made the original commit a few years back. Please stand by

**Comment by CKeilbar** [comment]
By the way, "yuhuig@gm*il DOT com" is not actually his real email address, and so he won't be able to sign the ECA using that address. I can get him to sign it using a different, third, email address though.

**Comment by DBees** [comment]
Thanks @CKeilbar understood. Here is the issue I opened with Eclipse EMO team to get their view on how we can handle this
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13476

**Comment by CKeilbar** [comment]
That URL doesn't seem to work for me; the issue might have private visibility (not that that is a problem). Please let me know if there is anything you want me to do.

**Comment by DBees** [comment]
Hi @CKeilbar has the original author of the commit now signed the ECA?

**Comment by gyh1997127** [comment]
I am the original author of the commit using the email address yuhuig@ensc-rcl-1.research.sfu.ca and yuhuig@gmail.com; I confirm that I have now signed the ECA under the email address gyh1997127@gmail.com. I confirm that I hold the copyright on the original contribution and I'm submitting it in accordance with the project license Apache 2.0

**Comment by MikeOpenHWGroup** [comment]
Hi @gyh1997127.  I can confirm that gyh1997127@gmail.com is covered by an ECA.  However, that email address is _not_ associated with this pull-request.  In order for us to accept a PR, the PR must be from a GitHub account that is associated with the email address covered by the ECA.

Having said that, your SFU email address (yuhuig@ensc-rcl-1.research.sfu.ca) _is_ covered, but for some reason, the Eclipse check is failing:
image

I will look into this.

**Comment by CKeilbar** [comment]
Hi @MikeOpenHWGroup, it will not be possible to sign the ECA under [yuhuig@ensc-rcl-1.research.sfu.ca](mailto:yuhuig@ensc-rcl-1.research.sfu.ca); that is the address of one of our internal research servers and not a real email address.

**Comment by MikeOpenHWGroup** [comment]
I reached out to Eclipse to investigate and their response was:
>   So it looks like there isn't an issue with the validation, but there does appear to be an issue in the 'display results' section, which is indicating that yuhuig@ensc.... has an ECA on file when in fact they do not.

So, there are two approaches here:
1. Close this PR and resubmit a new PR from an account that is known to be covered by the ECA.
2. Rebase this PR to edit the authorship to an account that is known to be covered by the EDA.

GitHub has excellent user documentation on rebasing ([link](https://docs.github.com/en/get-started/using-git/about-git-rebase)).

**Comment by CKeilbar** [comment]
Thanks for your followup @MikeOpenHWGroup. I have created a new PR (#26) that fixes this issue by choosing the first option, squashing the FPU commit history.

**Comment by CKeilbar** [comment]
This has been merged in #26.

**Pull request closed without merging**
